VT-3665 MPC Enhancements for Go SDK
plivo/plivo-go pull request #124
Opened 2021-11-02 08:39 UTC by Abinaya-Shunmugavel

2021-11-03 10:38 UTC, Koushik-Ayila requested changes
Also, please add the renamed mock response files as well

2021-11-03 10:38 UTC, Koushik-Ayila commented on multipartycall_test.go
> +	expectResponse("MPCStartParticipantRecordResponse.json", 202)
instead of 202, it should be 200

2021-11-03 10:38 UTC, Koushik-Ayila commented on multipartycall_test.go
> +	if response, err := client.MultiPartyCall.StartPlayAudio(MultiPartyCallParticipantParams{MpcUuid: "ebacced2-21ab-466d-9df4-67339991761b", ParticipantId: "209"}, MultiPartCallAudio{Url: "https://s3.a
Please make UT change here as well similar to that of code

2021-11-03 10:38 UTC, Koushik-Ayila commented on xml/plivoxml_test.go
> +			new(MultiPartyCallElement).SetAgentHoldMusicMethod("GET").SetCoachMode(true).SetCustomerHoldMusicMethod("GET").SetEndMpcOnExit(false).SetEnterSound("beep:1").SetEnterSoundMethod("GET").SetExitSoun
StartRecordingAudio and StopRecordingAudio should be URLs

2021-11-08 11:36 UTC, Koushik-Ayila requested changes

2021-11-08 11:36 UTC, Koushik-Ayila commented on multipartycall.go
> +type MultiPartCallAudioParams struct {
rename this to MultiPartyCallAudioParams

2021-11-08 11:36 UTC, Koushik-Ayila commented on multipartycall_test.go
> +	if response, err := client.MultiPartyCall.StartPlayAudio(MultiPartyCallParticipantParams{MpcUuid: "ebacced2-21ab-466d-9df4-67339991761b", ParticipantId: "209"}, MultiPartCallAudioParams{Url: "https:
please rename here as well

2021-11-08 11:36 UTC, Koushik-Ayila commented on xml/plivoxml_test.go
> +			new(MultiPartyCallElement).SetAgentHoldMusicMethod("GET").SetCoachMode(true).SetCustomerHoldMusicMethod("GET").SetEndMpcOnExit(false).SetEnterSound("beep:1").SetEnterSoundMethod("GET").SetExitSoun
url would mean some valid url

2021-11-08 13:46 UTC, Koushik-Ayila approved these changes

2021-11-17 09:35 UTC, varshit97plivo approved these changes

2021-11-22 07:56 UTC, varshit97plivo approved these changes

2021-11-23 05:32 UTC, merged