10DLC Enhancement Go SDK
plivo/plivo-go pull request #147
Opened 2022-09-07 05:21 UTC by NirmitiJain

2022-09-07 05:29 UTC, narayana-plivo requested changes
LGTM. Please add UT

2022-09-07 05:33 UTC, manas-plivo approved these changes

2022-10-12 03:06 UTC, narayana-plivo commented on brand.go
> +	ApiID string 		 `json:"api_id,omitempty"`
formatting required

2022-10-12 03:06 UTC, narayana-plivo approved these changes
LGTM

2022-10-17 10:10 UTC, merged